
SCREEN_WIDTH = 1250
SCREEN_HEIGHT = 750
SCREEN_COLOR = 'black'
SCREEN_DOT_LINE_COLOR  = 'white'

SCREEN_SIZE = (1200,700)

BALL_SHAPE = 'circle'
BALL_SIZE = 20
BALL_COLOR = 'white'
BALL_SPEED = 10



GAME_FIELD_Y = int(SCREEN_HEIGHT / 2 -  BALL_SIZE) 
GAME_FIELD_X = int(SCREEN_WIDTH / 2 -  BALL_SIZE )


PADDLE_LENGTH = 7
PADDLE_SIZE = 20

PADDLE_COLOR = 'white'
PADDLE_SHAPE = 'square'

